from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from html import escape
from pathlib import Path
from string import Template


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "resume_data.json"
GENERATED_COMMENT = "<!-- Generated by tools/build_resume.py. Edit data/resume_data.json instead. -->\n"


MAIN_TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>$title</title>
  <link rel="icon" type="image/x-icon" href="$favicon_href">
  <style>
    :root {
      --page-width: 210mm;
      --page-height: 297mm;
      --ink: #1b1b1b;
      --muted: #4f4f4f;
      --rule: #202020;
      --soft-rule: #b8b8b8;
    }

    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      background: #f5f5f5;
      color: var(--ink);
      font-family: Georgia, "Times New Roman", serif;
      line-height: 1.3;
    }

    .page {
      width: min(var(--page-width), 100%);
      min-height: var(--page-height);
      margin: 20px auto;
      background: #fff;
      padding: 16mm 16mm 15mm;
      box-shadow: 0 10px 36px rgba(0, 0, 0, 0.12);
    }

    .top {
      display: flex;
      justify-content: space-between;
      gap: 18px;
      align-items: flex-start;
      border-bottom: 1px solid var(--soft-rule);
      padding-bottom: 10px;
    }

    .identity {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    h1 {
      margin: 0;
      font-size: 31px;
      font-weight: 700;
      letter-spacing: 0.01em;
    }

    .actions {
      display: flex;
      align-items: center;
      flex-wrap: wrap;
      gap: 10px 14px;
    }

    .contact {
      font-size: 12px;
      color: var(--muted);
      text-align: right;
      white-space: nowrap;
    }

    .contact div + div {
      margin-top: 2px;
    }

    .contact a {
      color: inherit;
      text-decoration: none;
      border-bottom: 1px solid rgba(79, 79, 79, 0.35);
      transition: color 0.2s ease, border-bottom-color 0.2s ease;
    }

    .contact a:hover,
    .contact a:focus-visible {
      color: var(--ink);
      border-bottom-color: currentColor;
    }

    .profile-links {
      letter-spacing: 0.02em;
    }

    .resume-link {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      padding: 7px 12px;
      border: 1px solid var(--rule);
      color: var(--ink);
      text-decoration: none;
      font-size: 12px;
      font-weight: 700;
      letter-spacing: 0.04em;
      text-transform: uppercase;
      transition: background-color 0.2s ease, color 0.2s ease;
    }

    .resume-link:hover,
    .resume-link:focus-visible {
      background: var(--rule);
      color: #fff;
    }

    .secondary-link {
      color: var(--muted);
      text-decoration: none;
      font-size: 12px;
      letter-spacing: 0.05em;
      text-transform: uppercase;
      border-bottom: 1px solid rgba(79, 79, 79, 0.35);
      transition: color 0.2s ease, border-bottom-color 0.2s ease;
    }

    .secondary-link:hover,
    .secondary-link:focus-visible {
      color: var(--ink);
      border-bottom-color: currentColor;
    }

    .summary {
      margin: 12px 0 12px;
      padding-left: 12px;
      border-left: 3px solid var(--rule);
      font-size: 13px;
    }

    section {
      margin: 0 0 11px;
    }

    h2 {
      margin: 0 0 6px;
      font-size: 12px;
      letter-spacing: 0.14em;
      text-transform: uppercase;
      font-weight: 700;
      border-bottom: 1px solid var(--rule);
      padding-bottom: 3px;
    }

    .entry {
      margin-bottom: 8px;
    }

    .entry-head {
      display: flex;
      justify-content: space-between;
      align-items: baseline;
      gap: 10px;
      font-size: 13px;
      font-weight: 700;
    }

    .org-link {
      color: inherit;
      text-decoration: none;
      border-bottom: 1px solid rgba(27, 27, 27, 0.22);
      transition: border-bottom-color 0.2s ease, color 0.2s ease;
    }

    .org-link:hover,
    .org-link:focus-visible {
      color: var(--ink);
      border-bottom-color: currentColor;
    }

    .entry-sub {
      margin-top: 1px;
      font-size: 12.4px;
      font-style: italic;
      color: var(--muted);
    }

    .entry-note {
      margin-top: 3px;
      font-size: 11.8px;
      color: var(--muted);
    }

    ul {
      margin: 5px 0 0;
      padding-left: 18px;
      font-size: 12.2px;
    }

    li + li {
      margin-top: 4px;
    }

    .skill-list,
    .highlight-list {
      padding-left: 18px;
    }

    .skill-list li,
    .highlight-list li {
      margin-top: 3px;
    }

    .label {
      font-weight: 700;
    }

    @page {
      size: A4;
      margin: 10mm;
    }

    @media print {
      body {
        background: #fff;
      }

      .page {
        margin: 0 auto;
        box-shadow: none;
        width: 100%;
        min-height: auto;
        padding: 0;
      }

      .actions {
        display: none;
      }
    }

    @media (max-width: 760px) {
      .page {
        padding: 18px 16px;
        min-height: auto;
      }

      .top,
      .entry-head {
        display: block;
      }

      .contact {
        text-align: left;
        margin-top: 6px;
        white-space: normal;
      }
    }
  </style>
</head>
<body>
  <main class="page">
    <div class="top">
      <div class="identity">
        <h1>$name</h1>
        <div class="actions">
          <a class="resume-link" href="$pdf_wrapper_href" target="_blank" rel="noopener noreferrer">View PDF Resume</a>
          <a class="secondary-link" href="$ats_html_href">ATS Version</a>
        </div>
      </div>
      <div class="contact">
        <div><a href="mailto:$email">$email</a></div>
        <div class="profile-links">$profile_links</div>
        <div>$relocation</div>
        <div>$languages</div>
      </div>
    </div>

    <div class="summary">$summary</div>

    <section>
      <h2>Education</h2>
      $education_entries
    </section>

    <section>
      <h2>Skills</h2>
      <ul class="skill-list">
        $skill_items
      </ul>
    </section>

    <section>
      <h2>Professional Experience</h2>
      $experience_entries
    </section>

    <section>
      <h2>Selected Highlights</h2>
      <ul class="highlight-list">
        $highlight_items
      </ul>
    </section>
  </main>
</body>
</html>
"""
)


ATS_TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>$title</title>
  <link rel="icon" type="image/x-icon" href="$favicon_href">
  <style>
    :root {
      --page-width: 210mm;
      --ink: #111111;
      --muted: #333333;
      --rule: #222222;
    }

    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      background: #ffffff;
      color: var(--ink);
      font-family: Georgia, "Times New Roman", serif;
      line-height: 1.35;
    }

    .page {
      width: min(var(--page-width), 100%);
      margin: 0 auto;
      padding: 16mm;
    }

    .page-actions {
      margin-bottom: 10px;
    }

    .action-link {
      color: var(--muted);
      text-decoration: none;
      font-size: 12px;
      letter-spacing: 0.05em;
      text-transform: uppercase;
      border-bottom: 1px solid rgba(51, 51, 51, 0.35);
    }

    h1 {
      margin: 0 0 8px;
      font-size: 28px;
      line-height: 1.1;
    }

    .contact {
      font-size: 12px;
      color: var(--muted);
    }

    .contact div + div {
      margin-top: 2px;
    }

    .contact a {
      color: inherit;
      text-decoration: none;
    }

    .summary {
      margin: 14px 0 12px;
      font-size: 12.5px;
    }

    section {
      margin: 0 0 12px;
    }

    h2 {
      margin: 0 0 6px;
      font-size: 12px;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      font-weight: 700;
      border-bottom: 1px solid var(--rule);
      padding-bottom: 3px;
    }

    .entry {
      margin-bottom: 8px;
    }

    .entry-head {
      display: flex;
      justify-content: space-between;
      gap: 12px;
      align-items: baseline;
      font-size: 12.8px;
      font-weight: 700;
    }

    .entry-sub {
      margin-top: 1px;
      font-size: 12px;
      color: var(--muted);
      font-style: italic;
    }

    .entry-note {
      margin-top: 3px;
      font-size: 11.5px;
      color: var(--muted);
    }

    ul {
      margin: 5px 0 0;
      padding-left: 18px;
      font-size: 12px;
    }

    li + li {
      margin-top: 4px;
    }

    .label {
      font-weight: 700;
    }

    @page {
      size: A4;
      margin: 10mm;
    }

    @media print {
      .page {
        width: 100%;
        padding: 0;
      }

      .page-actions {
        display: none;
      }
    }

    @media (max-width: 760px) {
      .page {
        padding: 18px 16px;
      }

      .entry-head {
        display: block;
      }
    }
  </style>
</head>
<body>
  <main class="page">
    <div class="page-actions">
      <a class="action-link" href="$ats_pdf_wrapper_href" target="_blank" rel="noopener noreferrer">View ATS PDF</a>
    </div>

    <h1>$name</h1>

    <div class="contact">
      <div><a href="mailto:$email">$email</a></div>
      <div>$profile_line_ats</div>
      <div>$relocation</div>
      <div>$languages</div>
    </div>

    <div class="summary">$summary</div>

    <section>
      <h2>Education</h2>
      $education_entries
    </section>

    <section>
      <h2>Skills</h2>
      <ul>
        $skill_items
      </ul>
    </section>

    <section>
      <h2>Professional Experience</h2>
      $experience_entries
    </section>

    <section>
      <h2>Selected Highlights</h2>
      <ul>
        $highlight_items
      </ul>
    </section>
  </main>
</body>
</html>
"""
)


WRAPPER_TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>$title</title>
  <link rel="icon" type="image/x-icon" href="$favicon_href">
  <style>
    :root {
      --bg: #f5f5f5;
      --ink: #1b1b1b;
      --muted: #4f4f4f;
      --rule: #d6d6d6;
    }

    * {
      box-sizing: border-box;
    }

    html,
    body {
      height: 100%;
    }

    body {
      margin: 0;
      background: var(--bg);
      color: var(--ink);
      font-family: Georgia, "Times New Roman", serif;
    }

    .frame {
      width: 100%;
      height: 100%;
      border: 0;
      display: block;
    }

    .fallback {
      position: fixed;
      top: 16px;
      left: 16px;
      z-index: 1;
      padding: 8px 12px;
      background: rgba(255, 255, 255, 0.92);
      border: 1px solid var(--rule);
      color: var(--muted);
      font-size: 12px;
      line-height: 1.4;
    }

    .fallback a {
      color: inherit;
    }
  </style>
</head>
<body>
  <div class="fallback">
    If the PDF does not load automatically,
    <a href="$pdf_href" target="_blank" rel="noopener noreferrer">open it directly</a>.
  </div>
  <iframe class="frame" src="$pdf_href" title="$frame_title"></iframe>
</body>
</html>
"""
)


def load_data() -> dict:
    return json.loads(DATA_PATH.read_text(encoding="utf-8"))


def esc(value: str) -> str:
    return escape(value, quote=True)


def href(from_file: Path, target: Path, *, target_is_dir: bool = False) -> str:
    rel = os.path.relpath(target, start=from_file.parent).replace("\\", "/")
    if target_is_dir:
        if rel == ".":
            return "./"
        return rel.rstrip("/") + "/"
    return rel


def html_href(from_file: Path, target_file: Path) -> str:
    return os.path.relpath(target_file, start=from_file.parent).replace("\\", "/")


def render_main_profile_links(profiles: list[dict]) -> str:
    parts = []
    for profile in profiles:
        parts.append(
            '<a href="{url}" target="_blank" rel="noopener noreferrer">{label}</a>'.format(
                url=esc(profile["url"]),
                label=esc(profile["label"]),
            )
        )
    return '<span aria-hidden="true"> / </span>'.join(parts)


def render_ats_profile_line(profiles: list[dict]) -> str:
    parts = []
    for profile in profiles:
        parts.append(
            '{label}: <a href="{url}" target="_blank" rel="noopener noreferrer">{display}</a>'.format(
                label=esc(profile["label"]),
                url=esc(profile["url"]),
                display=esc(profile["display"]),
            )
        )
    return " | ".join(parts)


def render_org(name: str, url: str | None, link_class: str | None) -> str:
    if not url:
        return esc(name)
    class_attr = f' class="{esc(link_class)}"' if link_class else ""
    return '<a{class_attr} href="{url}" target="_blank" rel="noopener noreferrer">{name}</a>'.format(
        class_attr=class_attr,
        url=esc(url),
        name=esc(name),
    )


def render_education_entries(entries: list[dict], link_class: str | None) -> str:
    blocks: list[str] = []
    for entry in entries:
        blocks.append(
            "\n".join(
                [
                    '      <div class="entry">',
                    '        <div class="entry-head">',
                    f'          <div>{render_org(entry["organization"], entry.get("url"), link_class)}</div>',
                    f'          <div>{esc(entry["dates"])}</div>',
                    "        </div>",
                    f'        <div class="entry-sub">{esc(entry["subtitle"])}</div>',
                    f'        <div class="entry-note">{esc(entry["note"])}</div>' if entry.get("note") else "",
                    "      </div>",
                ]
            ).replace("\n\n", "\n")
        )
    return "\n".join(blocks)


def render_experience_entries(entries: list[dict], link_class: str | None) -> str:
    blocks: list[str] = []
    for entry in entries:
        bullets = "\n".join(
            '          <li><span class="label">{label}:</span> {text}</li>'.format(
                label=esc(bullet["label"]),
                text=esc(bullet["text"]),
            )
            for bullet in entry["bullets"]
        )
        blocks.append(
            "\n".join(
                [
                    '      <div class="entry">',
                    '        <div class="entry-head">',
                    f'          <div>{render_org(entry["organization"], entry.get("url"), link_class)}</div>',
                    f'          <div>{esc(entry["dates"])}</div>',
                    "        </div>",
                    f'        <div class="entry-sub">{esc(entry["role"])}</div>',
                    "        <ul>",
                    bullets,
                    "        </ul>",
                    "      </div>",
                ]
            )
        )
    return "\n".join(blocks)


def render_skill_items(skills: list[dict]) -> str:
    return "\n".join(
        '        <li><span class="label">{label}:</span> {value}</li>'.format(
            label=esc(item["label"]),
            value=esc(item["value"]),
        )
        for item in skills
    )


def render_highlight_items(items: list[str]) -> str:
    return "\n".join(f"        <li>{esc(item)}</li>" for item in items)


def render_main_html(data: dict, outputs: dict[str, Path]) -> str:
    site = data["site"]
    person = data["person"]
    return GENERATED_COMMENT + MAIN_TEMPLATE.substitute(
        title=esc(site["main_title"]),
        favicon_href=esc(href(outputs["main_html"], outputs["favicon"])),
        name=esc(person["name"]),
        pdf_wrapper_href=esc(html_href(outputs["main_html"], outputs["main_wrapper"])),
        ats_html_href=esc(html_href(outputs["main_html"], outputs["ats_html"])),
        email=esc(person["email"]),
        profile_links=render_main_profile_links(person["profiles"]),
        relocation=esc(person["relocation"]),
        languages=esc(person["languages"]),
        summary=esc(data["summary"]),
        education_entries=render_education_entries(data["education"], "org-link"),
        skill_items=render_skill_items(data["skills"]),
        experience_entries=render_experience_entries(data["experience"], "org-link"),
        highlight_items=render_highlight_items(data["highlights"]),
    )


def render_ats_html(data: dict, outputs: dict[str, Path]) -> str:
    site = data["site"]
    person = data["person"]
    return GENERATED_COMMENT + ATS_TEMPLATE.substitute(
        title=esc(site["ats_title"]),
        favicon_href=esc(href(outputs["ats_html"], outputs["favicon"])),
        ats_pdf_wrapper_href=esc(html_href(outputs["ats_html"], outputs["ats_wrapper"])),
        name=esc(person["name"]),
        email=esc(person["email"]),
        profile_line_ats=render_ats_profile_line(person["profiles"]),
        relocation=esc(person["relocation"]),
        languages=esc(person["languages"]),
        summary=esc(data["summary"]),
        education_entries=render_education_entries(data["education"], None),
        skill_items=render_skill_items(data["skills"]),
        experience_entries=render_experience_entries(data["experience"], None),
        highlight_items=render_highlight_items(data["highlights"]),
    )


def render_wrapper_html(data: dict, outputs: dict[str, Path], *, title: str, wrapper_key: str, pdf_key: str, frame_title: str) -> str:
    return GENERATED_COMMENT + WRAPPER_TEMPLATE.substitute(
        title=esc(title),
        favicon_href=esc(href(outputs[wrapper_key], outputs["favicon"])),
        pdf_href=esc(href(outputs[wrapper_key], outputs[pdf_key])),
        frame_title=esc(frame_title),
    )


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8", newline="\n")


def find_browser() -> str | None:
    candidates = [
        shutil.which("msedge"),
        shutil.which("msedge.exe"),
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
        shutil.which("chrome"),
        shutil.which("chrome.exe"),
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    ]
    for candidate in candidates:
        if candidate and Path(candidate).exists():
            return str(candidate)
    return None


def generate_pdf(browser: str, html_path: Path, pdf_path: Path) -> None:
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    command = [
        browser,
        "--headless",
        "--disable-gpu",
        "--allow-file-access-from-files",
        f"--print-to-pdf={pdf_path}",
        "--no-pdf-header-footer",
        html_path.resolve().as_uri(),
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        message = result.stderr.strip() or result.stdout.strip() or "unknown error"
        raise RuntimeError(f"PDF generation failed for {html_path.name}: {message}")


def cleanup_obsolete_files() -> None:
    obsolete = [
        ROOT / "resume.pdf",
        ROOT / "resume.html",
        ROOT / "resume_ats.html",
        ROOT / "cequnyang_cpp.pdf",
        ROOT / "cequnyang_cpp_ats.pdf",
        ROOT / "cequnyang_cpp_ats.html",
    ]
    for path in obsolete:
        if path.exists():
            path.unlink()


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate resume site pages and PDFs from one data source.")
    parser.add_argument("--skip-pdf", action="store_true", help="Only regenerate HTML outputs.")
    args = parser.parse_args()

    data = load_data()
    site = data["site"]

    outputs = {
        "favicon": ROOT / "assets" / site["favicon"],
        "main_html": ROOT / "index.html",
        "main_wrapper": ROOT / "resume" / "index.html",
        "ats_html": ROOT / "ats" / "index.html",
        "ats_wrapper": ROOT / "ats" / "resume" / "index.html",
        "main_pdf": ROOT / "assets" / "pdf" / site["pdf_filename"],
        "ats_pdf": ROOT / "assets" / "pdf" / site["ats_pdf_filename"],
    }

    if not outputs["favicon"].exists():
        print(f"Missing favicon asset: {outputs['favicon']}", file=sys.stderr)
        return 1

    write_text(outputs["main_html"], render_main_html(data, outputs))
    write_text(outputs["ats_html"], render_ats_html(data, outputs))
    write_text(
        outputs["main_wrapper"],
        render_wrapper_html(
            data,
            outputs,
            title=site["main_title"],
            wrapper_key="main_wrapper",
            pdf_key="main_pdf",
            frame_title=f'{data["person"]["name"]} Resume',
        ),
    )
    write_text(
        outputs["ats_wrapper"],
        render_wrapper_html(
            data,
            outputs,
            title=site["ats_title"],
            wrapper_key="ats_wrapper",
            pdf_key="ats_pdf",
            frame_title=f'{data["person"]["name"]} ATS Resume',
        ),
    )

    cleanup_obsolete_files()

    if args.skip_pdf:
        print("Generated HTML outputs only.")
        return 0

    browser = find_browser()
    if not browser:
        print("Generated HTML outputs, but no supported browser was found for PDF export.", file=sys.stderr)
        return 1

    generate_pdf(browser, outputs["main_html"], outputs["main_pdf"])
    generate_pdf(browser, outputs["ats_html"], outputs["ats_pdf"])

    print(
        "Generated index.html, resume/index.html, ats/index.html, ats/resume/index.html, "
        "assets/pdf/{main_pdf}, and assets/pdf/{ats_pdf}.".format(
            main_pdf=site["pdf_filename"],
            ats_pdf=site["ats_pdf_filename"],
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
