from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import unicodedata
from html import escape
from pathlib import Path
from string import Template


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "resume_data.json"
GENERATED_COMMENT = "<!-- Generated by tools/build_resume.py. Edit data/resume_data.json instead. -->\n"
TEXT_TRANSLATIONS = str.maketrans(
    {
        "\u00a0": " ",
        "\u2007": " ",
        "\u200b": None,
        "\u200c": None,
        "\u200d": None,
        "\u2010": "-",
        "\u2011": "-",
        "\u2012": "-",
        "\u2013": "-",
        "\u2014": "-",
        "\u2015": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2026": "...",
        "\u202f": " ",
        "\u2060": None,
        "\u2212": "-",
        "\ufeff": None,
    }
)


MAIN_TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>$title</title>
  <link rel="icon" type="$favicon_type" href="$favicon_href">
  <style>
    :root {
      --page-width: 210mm;
      --page-height: 297mm;
      --paper: #ffffff;
      --bg: #f3f2ee;
      --ink: #161616;
      --muted: #525252;
      --rule: #222222;
    }

    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      background: var(--bg);
      color: var(--ink);
      font-family: Georgia, "Times New Roman", serif;
      line-height: 1.24;
    }

    .page {
      width: min(var(--page-width), 100%);
      min-height: var(--page-height);
      margin: 20px auto;
      background: var(--paper);
      padding: 12mm 14mm 12mm;
      box-shadow: 0 10px 36px rgba(0, 0, 0, 0.12);
    }

    .masthead {
      text-align: center;
    }

    .page-actions {
      text-align: right;
      margin-bottom: 6px;
    }

    h1 {
      margin: 0;
      font-size: 34px;
      font-weight: 700;
      line-height: 1.05;
    }

    .name-copy {
      appearance: none;
      border: 0;
      background: none;
      padding: 0;
      margin: 0;
      font: inherit;
      color: inherit;
      cursor: pointer;
    }

    .name-copy:hover,
    .name-copy:focus-visible {
      color: var(--muted);
    }

    .contact-row,
    .meta-row {
      display: flex;
      justify-content: center;
      align-items: center;
      flex-wrap: wrap;
      gap: 4px 8px;
      color: var(--muted);
    }

    .contact-row {
      margin-top: 8px;
      font-size: 12px;
    }

    .meta-row {
      margin-top: 3px;
      font-size: 11.5px;
    }

    .contact-row a,
    .meta-row a {
      color: inherit;
      text-decoration: none;
    }

    .contact-item {
      display: inline-flex;
      align-items: center;
      gap: 4px;
    }

    .contact-icon {
      width: 11px;
      height: 11px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      flex: 0 0 auto;
      transform: translateY(0.5px);
    }

    .contact-icon svg {
      display: block;
      width: 100%;
      height: 100%;
    }

    .contact-row a:hover,
    .contact-row a:focus-visible,
    .meta-row a:hover,
    .meta-row a:focus-visible {
      text-decoration: underline;
    }

    .sep {
      color: #8a8a8a;
    }

    .action-link {
      color: var(--muted);
      text-decoration: none;
      font-size: 10.5px;
      letter-spacing: 0.06em;
      text-transform: uppercase;
      border-bottom: 1px solid rgba(82, 82, 82, 0.35);
    }

    .action-link:hover,
    .action-link:focus-visible {
      color: var(--ink);
      border-bottom-color: currentColor;
    }

    .summary {
      margin: 10px 0 14px;
      padding-bottom: 10px;
      font-size: 12.1px;
    }

    .summary::after {
      content: "";
      display: block;
      width: 100%;
      height: 1px;
      margin: 10px auto 0;
      background: var(--rule);
      opacity: 0.28;
    }

    section {
      margin: 0 0 10px;
    }

    h2 {
      margin: 0 0 6px;
      font-size: 12px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      font-variant: small-caps;
      font-weight: 400;
      border-bottom: 1px solid var(--rule);
      padding-bottom: 2px;
    }

    .section-initial {
      font-size: 14px;
      font-variant: normal;
    }

    .entry {
      margin-bottom: 8px;
    }

    .entry-head {
      display: flex;
      justify-content: space-between;
      align-items: baseline;
      gap: 12px;
    }

    .entry-title {
      font-size: 13.8px;
      font-weight: 700;
      flex: 1 1 auto;
      min-width: 0;
    }

    .org-link {
      color: inherit;
      text-decoration: none;
    }

    .org-link:hover,
    .org-link:focus-visible {
      text-decoration: underline;
    }

    .entry-date {
      font-size: 11.8px;
      color: var(--muted);
      font-style: italic;
      margin-left: auto;
      text-align: right;
      white-space: nowrap;
      flex: 0 0 auto;
    }

    .entry-sub {
      margin-top: 1px;
      font-size: 12.3px;
      font-style: italic;
      color: var(--muted);
    }

    .entry-note {
      margin: 4px 0 0 12px;
      font-size: 11.7px;
      line-height: 1.24;
    }

    .skill-lines {
      margin-top: 5px;
    }

    .skill-lines p {
      margin: 0 0 4px;
      font-size: 12.1px;
    }

    ul {
      margin: 4px 0 0;
      padding-left: 26px;
      font-size: 12.1px;
    }

    li + li {
      margin-top: 3px;
    }

    .label {
      font-weight: 700;
    }

    @page {
      size: A4;
      margin: 10mm;
    }

    @media print {
      body {
        background: #fff;
      }

      .page {
        margin: 0 auto;
        box-shadow: none;
        width: 100%;
        min-height: auto;
        padding: 0;
      }

      .page-actions {
        display: none;
      }
    }

    @media (max-width: 760px) {
      .page {
        padding: 18px 14px;
        min-height: auto;
      }

      h1 {
        font-size: 30px;
      }

      .entry-date {
        display: block;
        margin-top: 2px;
        white-space: normal;
      }
    }
  </style>
</head>
<body>
  <main class="page">
    <div class="page-actions">
      <a class="action-link" href="$pdf_wrapper_href" target="_blank" rel="noopener noreferrer">View PDF Resume</a>
      <span class="sep" aria-hidden="true">|</span>
      <a class="action-link" href="$ats_html_href">ATS Version</a>
    </div>

    <header class="masthead">
      <h1><button class="name-copy" type="button" data-copy-text="$name" aria-label="Copy name to clipboard" title="Click to copy">$name</button></h1>
      <div class="contact-row">$contact_line_main</div>
      <div class="meta-row">$meta_line</div>
    </header>

    <div class="summary">$summary</div>

    <section>
      <h2><span class="section-initial">E</span>DUCATION</h2>
      $education_entries
    </section>

    <section>
      <h2><span class="section-initial">S</span>KILLS</h2>
      <div class="skill-lines">
        $skill_items
      </div>
    </section>

    <section>
      <h2><span class="section-initial">E</span>XPERIENCE</h2>
      $experience_entries
    </section>

  </main>
  <script>
    (() => {
      async function copyText(text) {
        if (navigator.clipboard && window.isSecureContext) {
          await navigator.clipboard.writeText(text);
          return;
        }

        const field = document.createElement("textarea");
        field.value = text;
        field.setAttribute("readonly", "");
        field.style.position = "fixed";
        field.style.opacity = "0";
        document.body.appendChild(field);
        field.select();
        document.execCommand("copy");
        document.body.removeChild(field);
      }

      for (const button of document.querySelectorAll(".name-copy")) {
        button.addEventListener("click", async () => {
          const text = button.dataset.copyText || button.textContent || "";
          const originalTitle = button.title;
          try {
            await copyText(text);
            button.title = "Copied";
          } catch (error) {
            button.title = "Copy failed";
          }
          setTimeout(() => {
            button.title = originalTitle;
          }, 1200);
        });
      }
    })();
  </script>
</body>
</html>
"""
)


ATS_TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>$title</title>
  <link rel="icon" type="$favicon_type" href="$favicon_href">
  <style>
    :root {
      --page-width: 210mm;
      --ink: #161616;
      --muted: #4f4f4f;
      --rule: #222222;
    }

    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      background: #ffffff;
      color: var(--ink);
      font-family: Georgia, "Times New Roman", serif;
      line-height: 1.24;
    }

    .page {
      width: min(var(--page-width), 100%);
      margin: 0 auto;
      padding: 12mm 14mm 12mm;
    }

    .page-actions {
      text-align: right;
      margin-bottom: 6px;
    }

    .action-link {
      color: var(--muted);
      text-decoration: none;
      font-size: 10.5px;
      letter-spacing: 0.06em;
      text-transform: uppercase;
      border-bottom: 1px solid rgba(79, 79, 79, 0.35);
    }

    .action-link:hover,
    .action-link:focus-visible {
      color: var(--ink);
      border-bottom-color: currentColor;
    }

    .masthead {
      text-align: center;
    }

    h1 {
      margin: 0;
      font-size: 34px;
      line-height: 1.05;
    }

    .name-copy {
      appearance: none;
      border: 0;
      background: none;
      padding: 0;
      margin: 0;
      font: inherit;
      color: inherit;
      cursor: pointer;
    }

    .name-copy:hover,
    .name-copy:focus-visible {
      color: var(--muted);
    }

    .contact-row,
    .meta-row {
      display: flex;
      justify-content: center;
      align-items: center;
      flex-wrap: wrap;
      gap: 4px 8px;
      color: var(--muted);
    }

    .contact-row {
      margin-top: 8px;
      font-size: 12px;
    }

    .meta-row {
      margin-top: 3px;
      font-size: 11.5px;
    }

    .contact-row a,
    .meta-row a {
      color: inherit;
      text-decoration: none;
    }

    .contact-item {
      display: inline-flex;
      align-items: center;
      gap: 4px;
    }

    .contact-icon {
      width: 11px;
      height: 11px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      flex: 0 0 auto;
      transform: translateY(0.5px);
    }

    .contact-icon svg {
      display: block;
      width: 100%;
      height: 100%;
    }

    .sep {
      color: #8a8a8a;
    }

    .summary {
      margin: 10px 0 14px;
      padding-bottom: 10px;
      font-size: 12.1px;
    }

    .summary::after {
      content: "";
      display: block;
      width: 100%;
      height: 1px;
      margin: 10px auto 0;
      background: var(--rule);
      opacity: 0.28;
    }

    section {
      margin: 0 0 10px;
    }

    h2 {
      margin: 0 0 6px;
      font-size: 12px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      font-variant: small-caps;
      font-weight: 400;
      border-bottom: 1px solid var(--rule);
      padding-bottom: 2px;
    }

    .section-initial {
      font-size: 14px;
      font-variant: normal;
    }

    .entry {
      margin-bottom: 8px;
    }

    .entry-head {
      display: flex;
      justify-content: space-between;
      gap: 12px;
      align-items: baseline;
    }

    .entry-title {
      font-size: 13.8px;
      font-weight: 700;
      flex: 1 1 auto;
      min-width: 0;
    }

    .entry-date {
      font-size: 11.8px;
      color: var(--muted);
      font-style: italic;
      margin-left: auto;
      text-align: right;
      white-space: nowrap;
      flex: 0 0 auto;
    }

    .entry-sub {
      margin-top: 1px;
      font-size: 12.3px;
      color: var(--muted);
      font-style: italic;
    }

    .entry-note {
      margin: 4px 0 0 12px;
      font-size: 11.7px;
      line-height: 1.24;
    }

    .skill-lines {
      margin-top: 5px;
    }

    .skill-lines p {
      margin: 0 0 4px;
      font-size: 12.1px;
    }

    ul {
      margin: 4px 0 0;
      padding-left: 26px;
      font-size: 12.1px;
    }

    li + li {
      margin-top: 3px;
    }

    .label {
      font-weight: 700;
    }

    @page {
      size: A4;
      margin: 10mm;
    }

    @media print {
      .page {
        width: 100%;
        padding: 0;
      }

      .page-actions {
        display: none;
      }
    }

    @media (max-width: 760px) {
      .page {
        padding: 18px 14px;
      }

      h1 {
        font-size: 30px;
      }

      .entry-date {
        display: block;
        margin-top: 2px;
        white-space: normal;
      }
    }
  </style>
</head>
<body>
  <main class="page">
    <div class="page-actions">
      <a class="action-link" href="$ats_pdf_wrapper_href" target="_blank" rel="noopener noreferrer">View ATS PDF</a>
    </div>

    <header class="masthead">
      <h1><button class="name-copy" type="button" data-copy-text="$name" aria-label="Copy name to clipboard" title="Click to copy">$name</button></h1>
      <div class="contact-row">$contact_line_ats</div>
      <div class="meta-row">$meta_line</div>
    </header>

    <div class="summary">$summary</div>

    <section>
      <h2><span class="section-initial">E</span>DUCATION</h2>
      $education_entries
    </section>

    <section>
      <h2><span class="section-initial">S</span>KILLS</h2>
      <div class="skill-lines">
        $skill_items
      </div>
    </section>

    <section>
      <h2><span class="section-initial">E</span>XPERIENCE</h2>
      $experience_entries
    </section>

  </main>
  <script>
    (() => {
      async function copyText(text) {
        if (navigator.clipboard && window.isSecureContext) {
          await navigator.clipboard.writeText(text);
          return;
        }

        const field = document.createElement("textarea");
        field.value = text;
        field.setAttribute("readonly", "");
        field.style.position = "fixed";
        field.style.opacity = "0";
        document.body.appendChild(field);
        field.select();
        document.execCommand("copy");
        document.body.removeChild(field);
      }

      for (const button of document.querySelectorAll(".name-copy")) {
        button.addEventListener("click", async () => {
          const text = button.dataset.copyText || button.textContent || "";
          const originalTitle = button.title;
          try {
            await copyText(text);
            button.title = "Copied";
          } catch (error) {
            button.title = "Copy failed";
          }
          setTimeout(() => {
            button.title = originalTitle;
          }, 1200);
        });
      }
    })();
  </script>
</body>
</html>
"""
)


WRAPPER_TEMPLATE = Template(
    """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>$title</title>
  <link rel="icon" type="$favicon_type" href="$favicon_href">
  <style>
    :root {
      --bg: #f5f5f5;
      --ink: #1b1b1b;
      --muted: #4f4f4f;
      --rule: #d6d6d6;
    }

    * {
      box-sizing: border-box;
    }

    html,
    body {
      height: 100%;
    }

    body {
      margin: 0;
      background: var(--bg);
      color: var(--ink);
      font-family: Georgia, "Times New Roman", serif;
    }

    .frame {
      width: 100%;
      height: 100%;
      border: 0;
      display: block;
    }

    .fallback {
      position: fixed;
      top: 16px;
      left: 16px;
      z-index: 1;
      padding: 8px 12px;
      background: rgba(255, 255, 255, 0.92);
      border: 1px solid var(--rule);
      color: var(--muted);
      font-size: 12px;
      line-height: 1.4;
    }

    .fallback a {
      color: inherit;
    }
  </style>
</head>
<body>
  <div class="fallback">
    If the PDF does not load automatically,
    <a href="$pdf_href" target="_blank" rel="noopener noreferrer">open it directly</a>.
  </div>
  <iframe class="frame" src="$pdf_href" title="$frame_title"></iframe>
</body>
</html>
"""
)


def load_data() -> dict:
    return json.loads(DATA_PATH.read_text(encoding="utf-8"))


def sanitize_text(value: str) -> str:
    normalized = unicodedata.normalize("NFKC", value)
    normalized = normalized.translate(TEXT_TRANSLATIONS)
    return normalized.replace("\t", " ")


def esc_text(value: str) -> str:
    return escape(sanitize_text(value), quote=True)


def esc_attr(value: str) -> str:
    return escape(value, quote=True)


def href(from_file: Path, target: Path, *, target_is_dir: bool = False) -> str:
    rel = os.path.relpath(target, start=from_file.parent).replace("\\", "/")
    if target_is_dir:
        if rel == ".":
            return "./"
        return rel.rstrip("/") + "/"
    return rel


def html_href(from_file: Path, target_file: Path) -> str:
    return os.path.relpath(target_file, start=from_file.parent).replace("\\", "/")


def icon_mime_type(path: Path) -> str:
    types = {
        ".svg": "image/svg+xml",
        ".ico": "image/x-icon",
        ".png": "image/png",
    }
    return types.get(path.suffix.lower(), "image/x-icon")


def join_contact_items(items: list[str]) -> str:
    return ' <span class="sep" aria-hidden="true">|</span> '.join(items)


def render_contact_icon(kind: str) -> str:
    icons = {
        "email": (
            '<svg viewBox="0 0 16 16" aria-hidden="true">'
            '<rect x="1.5" y="3" width="13" height="10" rx="1" fill="none" stroke="currentColor" stroke-width="1.5"/>'
            '<path d="M2.5 4.5L8 8.5L13.5 4.5" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>'
            "</svg>"
        ),
        "github": (
            '<svg aria-hidden="true" focusable="false" viewBox="0 0 24 24" fill="currentColor">'
            '<path d="M10.226 17.284c-2.965-.36-5.054-2.493-5.054-5.256 0-1.123.404-2.336 1.078-3.144-.292-.741-.247-2.314.09-2.965.898-.112 2.111.36 2.83 1.01.853-.269 1.752-.404 2.853-.404 1.1 0 1.999.135 2.807.382.696-.629 1.932-1.1 2.83-.988.315.606.36 2.179.067 2.942.72.854 1.101 2 1.101 3.167 0 2.763-2.089 4.852-5.098 5.234.763.494 1.28 1.572 1.28 2.807v2.336c0 .674.561 1.056 1.235.786 4.066-1.55 7.255-5.615 7.255-10.646C23.5 6.188 18.334 1 11.978 1 5.62 1 .5 6.188.5 12.545c0 4.986 3.167 9.12 7.435 10.669.606.225 1.19-.18 1.19-.786V20.63a2.9 2.9 0 0 1-1.078.224c-1.483 0-2.359-.808-2.987-2.313-.247-.607-.517-.966-1.034-1.033-.27-.023-.359-.135-.359-.27 0-.27.45-.471.898-.471.652 0 1.213.404 1.797 1.235.45.651.921.943 1.483.943.561 0 .92-.202 1.437-.719.382-.381.674-.718.944-.943"/>'
            "</svg>"
        ),
        "linkedin": (
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" data-supported-dps="24x24" fill="currentColor" focusable="false" aria-hidden="true">'
            '<path d="M20.5 2h-17A1.5 1.5 0 002 3.5v17A1.5 1.5 0 003.5 22h17a1.5 1.5 0 001.5-1.5v-17A1.5 1.5 0 0020.5 2zM8 19H5v-9h3zM6.5 8.25A1.75 1.75 0 118.3 6.5a1.78 1.78 0 01-1.8 1.75zM19 19h-3v-4.74c0-1.42-.6-1.93-1.38-1.93A1.74 1.74 0 0013 14.19a.66.66 0 000 .14V19h-3v-9h2.9v1.3a3.11 3.11 0 012.7-1.4c1.55 0 3.36.86 3.36 3.66z"/>'
            "</svg>"
        ),
    }
    icon = icons.get(kind)
    if not icon:
        return ""
    return '<span class="contact-icon" aria-hidden="true">{icon}</span>'.format(icon=icon)


def render_contact_link(url: str, text: str, *, kind: str | None = None) -> str:
    icon = render_contact_icon(kind) if kind else ""
    return '<span class="contact-item">{icon}<a href="{url}" target="_blank" rel="noopener noreferrer">{text}</a></span>'.format(
        icon=icon,
        url=esc_attr(url),
        text=esc_text(text),
    )


def render_main_contact_line(person: dict) -> str:
    icon_map = {"github": "github", "linkedin": "linkedin"}
    items = [render_contact_link(f'mailto:{person["email"]}', person["email"], kind="email")]
    for profile in person["profiles"]:
        items.append(render_contact_link(profile["url"], profile["label"], kind=icon_map.get(profile["label"].lower())))
    return join_contact_items(items)


def render_ats_contact_line(person: dict) -> str:
    icon_map = {"github": "github", "linkedin": "linkedin"}
    items = [render_contact_link(f'mailto:{person["email"]}', person["email"], kind="email")]
    for profile in person["profiles"]:
        items.append(render_contact_link(profile["url"], profile["display"], kind=icon_map.get(profile["label"].lower())))
    return join_contact_items(items)


def render_meta_line(person: dict) -> str:
    items: list[str] = []
    if person.get("relocation"):
        items.append(esc_text(person["relocation"]))
    if person.get("languages"):
        items.append(esc_text(person["languages"]))
    return join_contact_items(items)


def render_org(name: str, url: str | None, link_class: str | None) -> str:
    if not url:
        return esc_text(name)
    class_attr = f' class="{esc_attr(link_class)}"' if link_class else ""
    return '<a{class_attr} href="{url}" target="_blank" rel="noopener noreferrer">{name}</a>'.format(
        class_attr=class_attr,
        url=esc_attr(url),
        name=esc_text(name),
    )


def render_education_entries(entries: list[dict], link_class: str | None) -> str:
    blocks: list[str] = []
    for entry in entries:
        blocks.append(
            "\n".join(
                [
                    '      <div class="entry">',
                    '        <div class="entry-head">',
                    f'          <div class="entry-title">{render_org(entry["organization"], entry.get("url"), link_class)}</div>',
                    f'          <div class="entry-date">{esc_text(entry["dates"])}</div>',
                    "        </div>",
                    f'        <div class="entry-sub">{esc_text(entry["subtitle"])}</div>',
                    f'        <div class="entry-note">{esc_text(entry["note"])}</div>' if entry.get("note") else "",
                    "      </div>",
                ]
            ).replace("\n\n", "\n")
        )
    return "\n".join(blocks)


def render_experience_entries(entries: list[dict], link_class: str | None) -> str:
    blocks: list[str] = []
    for entry in entries:
        bullets = "\n".join(
            '          <li><span class="label">{label}:</span> {text}</li>'.format(
                label=esc_text(bullet["label"]),
                text=esc_text(bullet["text"]),
            )
            for bullet in entry["bullets"]
        )
        blocks.append(
            "\n".join(
                [
                    '      <div class="entry">',
                    '        <div class="entry-head">',
                    f'          <div class="entry-title">{render_org(entry["organization"], entry.get("url"), link_class)}</div>',
                    f'          <div class="entry-date">{esc_text(entry["dates"])}</div>',
                    "        </div>",
                    f'        <div class="entry-sub">{esc_text(entry["role"])}</div>',
                    "        <ul>",
                    bullets,
                    "        </ul>",
                    "      </div>",
                ]
            )
        )
    return "\n".join(blocks)


def render_skill_items(skills: list[dict]) -> str:
    return "\n".join(
        '        <p><span class="label">{label}:</span> {value}</p>'.format(
            label=esc_text(item["label"]),
            value=esc_text(item["value"]),
        )
        for item in skills
    )


def render_highlight_items(items: list[str]) -> str:
    return "\n".join(f"        <li>{esc_text(item)}</li>" for item in items)


def render_main_html(data: dict, outputs: dict[str, Path]) -> str:
    site = data["site"]
    person = data["person"]
    return GENERATED_COMMENT + MAIN_TEMPLATE.substitute(
        title=esc_text(site["main_title"]),
        favicon_href=esc_attr(href(outputs["main_html"], outputs["favicon"])),
        favicon_type=esc_attr(icon_mime_type(outputs["favicon"])),
        name=esc_text(person["name"]),
        pdf_wrapper_href=esc_attr(html_href(outputs["main_html"], outputs["main_wrapper"])),
        ats_html_href=esc_attr(html_href(outputs["main_html"], outputs["ats_html"])),
        contact_line_main=render_main_contact_line(person),
        meta_line=render_meta_line(person),
        summary=esc_text(data["summary"]),
        education_entries=render_education_entries(data["education"], "org-link"),
        skill_items=render_skill_items(data["skills"]),
        experience_entries=render_experience_entries(data["experience"], "org-link"),
    )


def render_ats_html(data: dict, outputs: dict[str, Path]) -> str:
    site = data["site"]
    person = data["person"]
    return GENERATED_COMMENT + ATS_TEMPLATE.substitute(
        title=esc_text(site["ats_title"]),
        favicon_href=esc_attr(href(outputs["ats_html"], outputs["favicon"])),
        favicon_type=esc_attr(icon_mime_type(outputs["favicon"])),
        ats_pdf_wrapper_href=esc_attr(html_href(outputs["ats_html"], outputs["ats_wrapper"])),
        name=esc_text(person["name"]),
        contact_line_ats=render_ats_contact_line(person),
        meta_line=render_meta_line(person),
        summary=esc_text(data["summary"]),
        education_entries=render_education_entries(data["education"], None),
        skill_items=render_skill_items(data["skills"]),
        experience_entries=render_experience_entries(data["experience"], None),
    )


def render_wrapper_html(data: dict, outputs: dict[str, Path], *, title: str, wrapper_key: str, pdf_key: str, frame_title: str) -> str:
    return GENERATED_COMMENT + WRAPPER_TEMPLATE.substitute(
        title=esc_text(title),
        favicon_href=esc_attr(href(outputs[wrapper_key], outputs["favicon"])),
        favicon_type=esc_attr(icon_mime_type(outputs["favicon"])),
        pdf_href=esc_attr(href(outputs[wrapper_key], outputs[pdf_key])),
        frame_title=esc_text(frame_title),
    )


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8", newline="\n")


def find_browser() -> str | None:
    candidates = [
        shutil.which("msedge"),
        shutil.which("msedge.exe"),
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
        shutil.which("chrome"),
        shutil.which("chrome.exe"),
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    ]
    for candidate in candidates:
        if candidate and Path(candidate).exists():
            return str(candidate)
    return None


def generate_pdf(browser: str, html_path: Path, pdf_path: Path) -> None:
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    command = [
        browser,
        "--headless",
        "--disable-gpu",
        "--allow-file-access-from-files",
        f"--print-to-pdf={pdf_path}",
        "--no-pdf-header-footer",
        html_path.resolve().as_uri(),
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        message = result.stderr.strip() or result.stdout.strip() or "unknown error"
        raise RuntimeError(f"PDF generation failed for {html_path.name}: {message}")


def cleanup_obsolete_files() -> None:
    obsolete = [
        ROOT / "resume.pdf",
        ROOT / "resume.html",
        ROOT / "resume_ats.html",
        ROOT / "cequnyang_cpp.pdf",
        ROOT / "cequnyang_cpp_ats.pdf",
        ROOT / "cequnyang_cpp_ats.html",
    ]
    for path in obsolete:
        if path.exists():
            path.unlink()


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate resume site pages and PDFs from one data source.")
    parser.add_argument("--skip-pdf", action="store_true", help="Only regenerate HTML outputs.")
    args = parser.parse_args()

    data = load_data()
    site = data["site"]

    outputs = {
        "favicon": ROOT / "assets" / site["favicon"],
        "main_html": ROOT / "index.html",
        "main_wrapper": ROOT / "resume" / "index.html",
        "ats_html": ROOT / "ats" / "index.html",
        "ats_wrapper": ROOT / "ats" / "resume" / "index.html",
        "main_pdf": ROOT / "assets" / "pdf" / site["pdf_filename"],
        "ats_pdf": ROOT / "assets" / "pdf" / site["ats_pdf_filename"],
    }

    if not outputs["favicon"].exists():
        print(f"Missing favicon asset: {outputs['favicon']}", file=sys.stderr)
        return 1

    write_text(outputs["main_html"], render_main_html(data, outputs))
    write_text(outputs["ats_html"], render_ats_html(data, outputs))
    write_text(
        outputs["main_wrapper"],
        render_wrapper_html(
            data,
            outputs,
            title=site["main_title"],
            wrapper_key="main_wrapper",
            pdf_key="main_pdf",
            frame_title=f'{data["person"]["name"]} Resume',
        ),
    )
    write_text(
        outputs["ats_wrapper"],
        render_wrapper_html(
            data,
            outputs,
            title=site["ats_title"],
            wrapper_key="ats_wrapper",
            pdf_key="ats_pdf",
            frame_title=f'{data["person"]["name"]} ATS Resume',
        ),
    )

    cleanup_obsolete_files()

    if args.skip_pdf:
        print("Generated HTML outputs only.")
        return 0

    browser = find_browser()
    if not browser:
        print("Generated HTML outputs, but no supported browser was found for PDF export.", file=sys.stderr)
        return 1

    generate_pdf(browser, outputs["main_html"], outputs["main_pdf"])
    generate_pdf(browser, outputs["ats_html"], outputs["ats_pdf"])

    print(
        "Generated index.html, resume/index.html, ats/index.html, ats/resume/index.html, "
        "assets/pdf/{main_pdf}, and assets/pdf/{ats_pdf}.".format(
            main_pdf=site["pdf_filename"],
            ats_pdf=site["ats_pdf_filename"],
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
